# Generated by Django 3.0.5 on 2020-05-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMJob',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('long_status', models.CharField(max_length=500)),
                ('logs_available', models.BooleanField(default=False)),
            ],
        ),
    ]
