# Generated by Django 3.0.6 on 2020-05-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMJob',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=20)),
                ('iteration', models.IntegerField(default=-1)),
                ('status', models.CharField(max_length=20)),
                ('long_status', models.CharField(max_length=500)),
                ('logs_available', models.BooleanField(default=False)),
                ('labeling_url', models.URLField(max_length=500)),
            ],
        ),
    ]
